### ISSUE TITLE
Publish loaders as separate npm packages

### ISSUE THREAD

**Issue by JakobJingleheimer** [JakobJingleheimer/nodejs-loaders#19]
Currently, if a user wants just 1 of these loaders, they must install all of them and all of their dependencies. For example, `text` has no dependencies and `alias` has just 1 dependency (`lodash.get`), but to use either, users must install the deps for `css-module` & `tsx`.

I've created the org in npm: https://www.npmjs.com/org/nodejs-loaders

And also reserved the GH org `@nodejs-loaders` if needed, but I think it would be better to convert this to a monorepo.

**Comment by AugustinMauroy** [comment]
+1 for that and monorepo is good idea
