### ISSUE TITLE
Remove `alias` loader support for pjson.alias a& recommend pjson.imports

### ISSUE THREAD

**Issue by JakobJingleheimer** [JakobJingleheimer/nodejs-loaders#20]
The current `alias` field is obsolete with [package.json subimports](https://nodejs.org/api/packages.html#subpath-imports)

**Comment by AugustinMauroy** [comment]
-1 to remove it but why not add mention. Because there some framework put alias on their boilerplate (nextjs, gatsby, remix, nuxt)

**Comment by JakobJingleheimer** [comment]
Hmm? I'm not proposing removing the whole loader, just the part that looks for an "aliases" within package.json (because it's now redundant to the standard "imports" field).

**Comment by AugustinMauroy** [comment]
maybe just drop support of alias in `package.json`

**Comment by JakobJingleheimer** [comment]
Ah! Yes, should do as part of the v2.0 release. Good catch. Will try to get done today (unless you wanna do—should be just deleting a few lines of code, the test cases for it, and removing part of the readme).
