### ISSUE TITLE
`css-parse` -> `css` throw deprecated warn

### ISSUE THREAD

**Issue by AugustinMauroy** [JakobJingleheimer/nodejs-loaders#4]
`css` npm package wasn't maintained for 4 year. also I didn't found any way with `ccs` to parse nested css.

So one solution it's to use `@adobe/css-tools`
other solution is [`lightningcss`](https://lightningcss.dev/docs.html)

**Comment by AugustinMauroy** [comment]
EDIT: there are no nested css support [ref](https://github.com/adobe/css-tools/issues/122)

**Comment by JakobJingleheimer** [comment]
Ah, okay. This feature [CSS nesting selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector) did not exist when this loader was created.

I would say this feature is largely superfluous and is better addressed with css-modules (for which esbuild has built-in support).

Buuut it is spec'd, so I'll look for a replacement. The underlying lib I used is indeed unmaintained but it did what it needed to do (quite well and efficiently) for quite some time (I've been using this loader for like 4 years). Lightning is rather unstable—its releases are not infrequently broken.

**Comment by AugustinMauroy** [comment]
I had do some experimentation with `esbuild`, `@adobe/css-tools`, `Lightningcss` and `postcss`.
So here [the branch](https://github.com/AugustinMauroy/nodejs-loaders/tree/experiment). nothing has changed in terms of the spec.

But node_module size change 🎉

> Note:
> install all dependencies in the project root directory so it's also with devDependencies

main: `15,7`mo
experiment: `15,1`mo

**Comment by JakobJingleheimer** [comment]
W00t! I left a couple comments on that branch. It generally looks 👍 Do you wanna open a PR with it?

**Comment by AugustinMauroy** [comment]
> Do you wanna open a PR with it?

At first it was an experiment, but if you like it, here you go #7

**Comment by JakobJingleheimer** [comment]
Resolved by #7
